[book]
authors = ["Qase Support"]
language = "en"
multilingual = false
src = "src"
title = "Qase API Reporters"


[output.html]
# theme = "my-theme"
default-theme = "rust"
preferred-dark-theme = "navy"
smart-punctuation = true
# mathjax-support = false
# copy-fonts = true
# additional-css = ["custom.css", "custom2.css"]
# additional-js = ["custom.js"]
no-section-label = true
git-repository-url = "https://github.com/qase-tms"
git-repository-icon = "fa-github"
# edit-url-template = "https://github.com/rust-lang/mdBook/edit/master/guide/{path}"
# site-url = "/example-book/"
cname = "reporters.qase.io"
# input-404 = "not-found.md"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.code.hidelines]
python = "//"
py = "//"
javascript = "//"
js = "//"
java = "//"
typescript = "//"
ts = "//"
bash = "//"

[output.html.playground]
editable = true
line-numbers = true
